# Generated by Django 2.1.7 on 2020-05-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='index',
        ),
    ]
