# Generated by Django 2.1.7 on 2020-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_banner_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=0, verbose_name='轮播顺序'),
        ),
    ]
