# Generated by Django 2.1.7 on 2019-04-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '商品品牌', 'verbose_name_plural': '商品品牌'},
        ),
    ]
