# Generated by Django 2.1.7 on 2019-09-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='media/message/images/', verbose_name='上传的文件'),
        ),
    ]
